<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KN2Q89G" failures="1" tests="4" name="test" time="29.599" errors="0" timestamp="2024-02-29T21:20:08 IST">
  <testcase classname="com.gpn.test.HomePageTest" name="test4" time="4.611">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="com.gpn.test.LoginTest" name="test1" time="7.089"/>
  <testcase classname="com.gpn.test.LoginTest" name="test2" time="8.143"/>
  <testcase classname="com.gpn.test.HomePageTest" name="test3" time="0.471">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.gpn.test.HomePageTest.test3(HomePageTest.java:19)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- test -->
