<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-29T21:19:38 IST" name="Suite" finished-at="2024-02-29T21:20:08 IST" duration-ms="29599">
    <groups>
    </groups>
    <test started-at="2024-02-29T21:19:38 IST" name="test" finished-at="2024-02-29T21:20:08 IST" duration-ms="29599">
      <class name="com.gpn.test.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.gpn.test.LoginTest@34a3d150]" started-at="2024-02-29T21:19:39 IST" name="setup" finished-at="2024-02-29T21:19:55 IST" duration-ms="16008" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.gpn.test.LoginTest@34a3d150]" started-at="2024-02-29T21:19:39 IST" name="setup" finished-at="2024-02-29T21:19:54 IST" duration-ms="14928" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test1()[pri:0, instance:com.gpn.test.LoginTest@34a3d150]" started-at="2024-02-29T21:19:54 IST" name="test1" finished-at="2024-02-29T21:20:01 IST" duration-ms="7089" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test2()[pri:0, instance:com.gpn.test.LoginTest@34a3d150]" started-at="2024-02-29T21:19:55 IST" name="test2" finished-at="2024-02-29T21:20:03 IST" duration-ms="8143" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.gpn.test.LoginTest@34a3d150]" started-at="2024-02-29T21:20:01 IST" name="tearDown" finished-at="2024-02-29T21:20:08 IST" duration-ms="6897" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.gpn.test.LoginTest@34a3d150]" started-at="2024-02-29T21:20:03 IST" name="tearDown" finished-at="2024-02-29T21:20:08 IST" duration-ms="5074" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.gpn.test.LoginTest -->
      <class name="com.gpn.test.HomePageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.gpn.test.HomePageTest@5b7a5baa]" started-at="2024-02-29T21:19:39 IST" name="setup" finished-at="2024-02-29T21:19:55 IST" duration-ms="16678" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.gpn.test.HomePageTest@5b7a5baa]" started-at="2024-02-29T21:19:39 IST" name="setup" finished-at="2024-02-29T21:20:06 IST" duration-ms="27365" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test4()[pri:0, instance:com.gpn.test.HomePageTest@5b7a5baa]" started-at="2024-02-29T21:19:55 IST" name="test4" finished-at="2024-02-29T21:20:00 IST" duration-ms="4611" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping this exception
at com.gpn.test.HomePageTest.test4(HomePageTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.gpn.test.HomePageTest@5b7a5baa]" started-at="2024-02-29T21:20:00 IST" name="tearDown" finished-at="2024-02-29T21:20:08 IST" duration-ms="7889" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="test3()[pri:0, instance:com.gpn.test.HomePageTest@5b7a5baa]" started-at="2024-02-29T21:20:06 IST" name="test3" finished-at="2024-02-29T21:20:07 IST" duration-ms="471" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at com.gpn.test.HomePageTest.test3(HomePageTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.gpn.test.HomePageTest@5b7a5baa]" started-at="2024-02-29T21:20:07 IST" name="tearDown" finished-at="2024-02-29T21:20:08 IST" duration-ms="1291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.gpn.test.HomePageTest -->
    </test> <!-- test -->
  </suite> <!-- Suite -->
</testng-results>
